import type { ArrayExpression, CallExpression, File, Node } from "@babel/types";
import { getModuleReferences } from "./imports";
import { tryParseModule, unwrapExpression, walk } from "./parse";
import { applyEdits, indentationAt, lineOf, TextEdit } from "./splice";

const ROUTES_MODULE = "@react-router/dev/routes";

export interface RouteEntry {
  path: string;
  file: string;
}

type Analysis =
  | {
      ok: true;
      ast: File;
      array: ArrayExpression;
      routeLocal: string | null;
      /** Top-level `route("*", ...)` */
      splat: CallExpression | null;
      nestedSplat: boolean;
      calls: { path: string | null; file: string | null; topLevel: boolean }[];
    }
  | { ok: false; reason: "parse_error" | "unsupported_shape"; detail: string };

const stringArg = (call: CallExpression, index: number) => {
  const arg = call.arguments[index];
  return arg?.type === "StringLiteral" ? arg.value : null;
};

const isRouteCall = (
  node: Node,
  routeLocal: string | null
): node is CallExpression =>
  node.type === "CallExpression" &&
  node.callee.type === "Identifier" &&
  routeLocal !== null &&
  node.callee.name === routeLocal;

export const analyzeRoutes = (code: string, filename: string): Analysis => {
  const ast = tryParseModule(code, filename);
  if (!ast)
    return {
      ok: false,
      reason: "parse_error",
      detail: `Could not parse ${filename}`,
    };

  const exportDefault = ast.program.body.find(
    (s) => s.type === "ExportDefaultDeclaration"
  );
  if (!exportDefault || exportDefault.type !== "ExportDefaultDeclaration") {
    return {
      ok: false,
      reason: "unsupported_shape",
      detail: "No default export",
    };
  }

  const exported = unwrapExpression(exportDefault.declaration as Node);
  if (exported.type !== "ArrayExpression") {
    return {
      ok: false,
      reason: "unsupported_shape",
      detail:
        exported.type === "CallExpression"
          ? "Routes are generated by a function (e.g. flatRoutes())"
          : "The default export is not an array literal",
    };
  }

  let routeLocal: string | null = null;
  for (const ref of getModuleReferences(ast, code)) {
    if (ref.kind !== "import" || ref.source !== ROUTES_MODULE) continue;
    const spec = ref.specifiers.find(
      (s) => s.imported === "route" && !s.typeOnly
    );
    if (spec) routeLocal = spec.local;
  }

  let splat: CallExpression | null = null;
  let nestedSplat = false;
  const calls: {
    path: string | null;
    file: string | null;
    topLevel: boolean;
  }[] = [];
  const topLevel = new Set<Node>(exported.elements.filter(Boolean) as Node[]);

  walk(exported, (node) => {
    if (!isRouteCall(node, routeLocal)) return;
    const path = stringArg(node, 0);
    const isTop = topLevel.has(node);
    calls.push({ path, file: stringArg(node, 1), topLevel: isTop });
    if (path === "*") {
      if (isTop) splat = node;
      else nestedSplat = true;
    }
  });

  return {
    ok: true,
    ast,
    array: exported,
    routeLocal,
    splat,
    nestedSplat,
    calls,
  };
};

/**
 * A route counts as registered if its module is, or if its (non catch-all)
 * path is already taken. A different catch-all is a conflict, not a match.
 */
const isSameRoute = (
  call: { path: string | null; file: string | null },
  entry: RouteEntry
) =>
  (call.file !== null && call.file === entry.file) ||
  (entry.path !== "*" && call.path === entry.path);

export const hasRoute = (code: string, filename: string, entry: RouteEntry) => {
  const analysis = analyzeRoutes(code, filename);
  if (!analysis.ok) return false;
  return analysis.calls.some((c) => isSameRoute(c, entry));
};

export type InsertResult =
  | { status: "inserted"; code: string; line: number; text: string }
  | { status: "exists" }
  | {
      status: "manual";
      reason: "conflict" | "unsupported_shape";
      detail: string;
    };

const bindsName = (ast: File, name: string) =>
  ast.program.body.some((s) => {
    if (s.type === "ImportDeclaration") {
      return s.specifiers.some((spec) => spec.local.name === name);
    }
    if (s.type === "VariableDeclaration") {
      return s.declarations.some(
        (d) => d.id.type === "Identifier" && d.id.name === name
      );
    }
    if (
      (s.type === "FunctionDeclaration" || s.type === "ClassDeclaration") &&
      s.id
    ) {
      return s.id.name === name;
    }
    return false;
  });

/**
 * Adds `route(path, file)` to a React Router `routes.ts` by splicing text at
 * AST-derived offsets. The user's formatting is preserved byte-for-byte and
 * the result is re-parsed to prove the entry was registered.
 */
export const insertRoute = (
  code: string,
  filename: string,
  entry: RouteEntry,
  opts: { position: "before-splat" | "end"; rejectExistingSplat?: boolean }
): InsertResult => {
  const analysis = analyzeRoutes(code, filename);
  if (!analysis.ok) {
    return {
      status: "manual",
      reason: "unsupported_shape",
      detail: analysis.detail,
    };
  }

  if (analysis.calls.some((c) => isSameRoute(c, entry))) {
    return { status: "exists" };
  }

  if (opts.rejectExistingSplat && (analysis.splat || analysis.nestedSplat)) {
    return {
      status: "manual",
      reason: "conflict",
      detail: 'A catch-all route ("*") is already registered',
    };
  }

  const edits: TextEdit[] = [];
  let routeLocal = analysis.routeLocal;

  if (!routeLocal) {
    if (bindsName(analysis.ast, "route")) {
      return {
        status: "manual",
        reason: "unsupported_shape",
        detail: "`route` is already declared in this file",
      };
    }

    routeLocal = "route";
    const refs = getModuleReferences(analysis.ast, code);
    const valueImport = refs.find(
      (r) =>
        r.kind === "import" &&
        r.source === ROUTES_MODULE &&
        !r.typeOnly &&
        r.specifiers.length > 0 &&
        r.specifiers.every((s) => s.kind === "named")
    );

    if (valueImport) {
      const decl = analysis.ast.program.body.find(
        (s) => s.start === valueImport.statementStart
      );
      const specifiers =
        decl?.type === "ImportDeclaration" ? decl.specifiers : [];
      const last = specifiers[specifiers.length - 1];
      edits.push({ start: last.end!, end: last.end!, text: ", route" });
    } else {
      const imports = analysis.ast.program.body.filter(
        (s) => s.type === "ImportDeclaration"
      );
      const quote = refs[0]?.quote ?? '"';
      const statement = `import { route } from ${quote}${ROUTES_MODULE}${quote};`;
      if (imports.length > 0) {
        const lastImport = imports[imports.length - 1];
        edits.push({
          start: lastImport.end!,
          end: lastImport.end!,
          text: `\n${statement}`,
        });
      } else {
        edits.push({ start: 0, end: 0, text: `${statement}\n` });
      }
    }
  }

  const { array } = analysis;
  const elements = array.elements.filter(Boolean) as Node[];
  // Match the quote style of the existing entries
  let q = '"';
  walk(array, (n) => {
    if (n.type === "StringLiteral" && q === '"' && code[n.start!] === "'")
      q = "'";
  });
  const text = `${routeLocal}(${q}${entry.path}${q}, ${q}${entry.file}${q})`;
  const singleLine = lineOf(code, array.start!) === lineOf(code, array.end!);

  let insertAt: number;
  let inserted: string;

  if (elements.length === 0) {
    insertAt = array.start! + 1;
    inserted = singleLine
      ? text
      : `\n${indentationAt(code, array.start!)}  ${text},`;
  } else if (opts.position === "before-splat" && analysis.splat) {
    insertAt = analysis.splat.start!;
    inserted = singleLine
      ? `${text}, `
      : `${text},\n${indentationAt(code, insertAt)}`;
  } else {
    const last = elements[elements.length - 1];
    const between = code.slice(last.end!, array.end! - 1);
    const commaIndex = between.indexOf(",");
    const hasTrailingComma =
      commaIndex !== -1 && between.slice(0, commaIndex).trim() === "";

    if (singleLine) {
      insertAt = last.end!;
      inserted = `, ${text}`;
    } else if (hasTrailingComma) {
      insertAt = last.end! + commaIndex + 1;
      inserted = `\n${indentationAt(code, last.start!)}${text},`;
    } else {
      insertAt = last.end!;
      inserted = `,\n${indentationAt(code, last.start!)}${text}`;
    }
  }

  edits.push({ start: insertAt, end: insertAt, text: inserted });
  const next = applyEdits(code, edits);

  if (!hasRoute(next, filename, entry)) {
    return {
      status: "manual",
      reason: "unsupported_shape",
      detail: "Could not verify the route after editing",
    };
  }

  return {
    status: "inserted",
    code: next,
    line: lineOf(next, next.indexOf(text)),
    text,
  };
};
