/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SplatRouteRouteImport } from "./routes/$.route";
import { Route as ApiPuckSplatRouteImport } from "./routes/api.puck.$";

const SplatRouteRoute = SplatRouteRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiPuckSplatRoute = ApiPuckSplatRouteImport.update({
  id: "/api/puck/$",
  path: "/api/puck/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/$": typeof SplatRouteRoute;
  "/api/puck/$": typeof ApiPuckSplatRoute;
}
export interface FileRoutesByTo {
  "/$": typeof SplatRouteRoute;
  "/api/puck/$": typeof ApiPuckSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/$": typeof SplatRouteRoute;
  "/api/puck/$": typeof ApiPuckSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/$" | "/api/puck/$";
  fileRoutesByTo: FileRoutesByTo;
  to: "/$" | "/api/puck/$";
  id: "__root__" | "/$" | "/api/puck/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  SplatRouteRoute: typeof SplatRouteRoute;
  ApiPuckSplatRoute: typeof ApiPuckSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof SplatRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/puck/$": {
      id: "/api/puck/$";
      path: "/api/puck/$";
      fullPath: "/api/puck/$";
      preLoaderRoute: typeof ApiPuckSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRouteRoute: SplatRouteRoute,
  ApiPuckSplatRoute: ApiPuckSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
