# This workflow will run all checks required for a PR to be merged.

name: Build and Test ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Check linting and formatting
        run: |
          if pnpm lint && pnpm format:check; then
            echo "Linting and formatting checks passed."
          else
            echo "Linting or formatting checks failed. Please fix the issues."
            exit 1
          fi

      - name: Build everything
        run: |
          pnpm build

      - name: Check for build failures
        run: |
          if [ $? -ne 0 ]; then
            echo "Build failed. Please fix the issues."
            exit 1
          fi
